notifications:
  email: false

sudo: required

services:
  - docker

env:
  global:
    - DOCKER_REPO=ivanilves

install:
  - docker pull ${DOCKER_REPO}/xiri-ubuntu
  - docker pull ${DOCKER_REPO}/xiri-centos

script:
  - testing/run_integration_case.sh zero
  - testing/run_integration_case.sh basic_connectivity_with_ssh
  - testing/run_integration_case.sh connect_with_ssh_agent
  - testing/run_integration_case.sh connect_with_ssh_key
  - testing/run_integration_case.sh do_client_teardown
  - testing/run_integration_case.sh do_server_teardown
  - testing/run_integration_case.sh run_with_dns_propagation
  - testing/run_integration_case.sh run_without_dns_propagation
  - testing/run_integration_case.sh run_with_reconnection
  - testing/run_integration_case.sh run_without_reconnection
  - testing/run_integration_case.sh run_with_route_discovery

branches:
  only:
    - master
